-- 債権管理システム 初期スキーマ（参考用）
-- 実運用のテーブル作成は Hibernate ddl-auto=update が担当します。
-- docker-compose からは自動実行しません（手動確認用）。
--
-- 利用する場合は APP_USER(receivables) で接続して実行してください。

CREATE TABLE customers (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR2(32)  NOT NULL UNIQUE,
    name          VARCHAR2(200) NOT NULL,
    contact_name  VARCHAR2(100),
    email         VARCHAR2(200),
    phone         VARCHAR2(50),
    credit_limit  NUMBER(18,0) DEFAULT 0,
    status        VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP
);

CREATE TABLE receivables (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no    VARCHAR2(40)  NOT NULL UNIQUE,
    customer_id   NUMBER        NOT NULL REFERENCES customers(id),
    invoice_date  DATE          NOT NULL,
    due_date      DATE          NOT NULL,
    amount        NUMBER(18,2)  NOT NULL,
    balance       NUMBER(18,2)  NOT NULL,
    currency      VARCHAR2(3)   NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    description   VARCHAR2(500),
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP
);

CREATE TABLE payments (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receivable_id  NUMBER       NOT NULL REFERENCES receivables(id),
    payment_date   DATE         NOT NULL,
    amount         NUMBER(18,2) NOT NULL,
    method         VARCHAR2(30) NOT NULL,
    reference_no   VARCHAR2(80),
    note           VARCHAR2(500),
    created_at     TIMESTAMP    NOT NULL
);

CREATE INDEX idx_receivables_customer ON receivables(customer_id);
CREATE INDEX idx_receivables_status ON receivables(status);
CREATE INDEX idx_payments_receivable ON payments(receivable_id);
